// ChecksumDlg.h : header file
//

#pragma once
#include "afxwin.h"
#include "afxcmn.h"
#include "selectfile1.h"


// CChecksumDlg dialog
class CChecksumDlg : public CDialog
{
// Construction
public:
	CChecksumDlg(CWnd* pParent = NULL);	// standard constructor

// Dialog Data
	enum { IDD = IDD_CHECKSUM_DIALOG };

	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support


// Implementation
protected:
	HICON m_hIcon;

	// Generated message map functions
	virtual BOOL OnInitDialog();
	afx_msg void OnSysCommand(UINT nID, LPARAM lParam);
	afx_msg void OnPaint();
	afx_msg HCURSOR OnQueryDragIcon();
	DECLARE_MESSAGE_MAP()
public:
	afx_msg void OnBnClickedChecksum();
	//test function definition
	afx_msg int Check(CString *pm_path);
	//Dos swizzle checkbox clicked
	afx_msg void OnBnClickedDosswizzle();
	// member variable for the IDC_OUTPUT list box control
	CListBox m_Output;
	// member variable stores full file name
	CString m_path;
	//member variable flag for Dos Swizzle Checkbox
	BOOL m_dosswizzle;
	//autogenerated function--something to do with ActiveX Browse dialog.
	DECLARE_EVENTSINK_MAP()
	//function is run on completetion of file selection in Browse window.
	void SelectionCompleteSelectfile1();
	CSelectfile1 m_selectfile;
	BOOL m_2BSwitch;
	BOOL m_4BSwitch;
	afx_msg void OnBnClicked2bswitch();
};
